#Issue 3 - Attempt to add support for ENV
JerryCauser/next-compose pull request #5
Opened 2019-11-26 22:06 UTC by actimetal96

[26/11/2019 - Diogo Azevedo]

Attempt to add support for "env".

2019-11-27 10:37 UTC, satazor commented on index.js
> +// 26/11/2019 - Diogo Azevedo
It's not usual to have the date and your name in code.

2019-11-27 10:40 UTC, satazor commented
You forgot to update the documentation mentioning we can now have `env`.

Moreover, please reference the issue in the commit body like so: "Closes #3"

2019-11-27 10:40 UTC, satazor requested changes

2019-11-27 10:40 UTC, satazor commented on index.js
> +//added support for env
This comment seems unnecessary to me.

2019-11-27 10:40 UTC, satazor commented on index.js
> +// 26/11/2019 - Diogo Azevedo
It's not usual to have the date and your name in code.

2019-11-27 10:40 UTC, satazor commented on index.js
> +  env(config){
To keep consistency with the rest of the code, add a space before the brackets.

2019-11-27 10:40 UTC, satazor commented on index.js
> +      if (plugin && plugin.env instanceof Function) {
I think `env` is an object that we should mixin with all the others. At least that's what I interpreted from #3

2019-11-27 10:55 UTC, actimetal96 commented
Thank you for your feedback @satazor ,  working on a proprietary solution right now, it is common to leave your name/date when some major fix or feature is implemented, I guess some old habits are bad habits! Also, I didn't add documentation because I was not sure that my changes would add support for the "env", then I wouldn't write something that the project could do, but in reality, it couldn't.
I am going to fix everything regarding your feedback.
Thanks again

2020-11-06 06:13 UTC, JerryCauser commented
Sorry, but `env` is just field in the `next.config.js`. There is no reason in that code here. Just use spread operator or Object.assign to insert static fields in result config.

2020-11-06 06:13 UTC, closed without merging